const TYPES = {
    ADD_TO_LIST: "ADD_TO_LIST",
    CALCULATE_TOTAL_PRICE_OF_THE_LIST: "CALCULATE_TOTAL_PRICE_OF_THE_LIST",
    DELETE_ALL_FROM_LIST: "DELETE_ALL_FROM_LIST",
    DELETE_EMPLOYER_FROM_LIST: "DELETE_EMPLOYER_FROM_LIST",
}

export default TYPES;